### ISSUE TITLE
Generate joint angles and joint angular rates from the 2015 walking data set

### ISSUE THREAD

**Issue by moorepants** [mechmotum/gait-closed-loop-id#2]
We have the data from "An elaborate data set on human gait and the effect of mechanical perturbations" https://peerj.com/articles/918/ and it is stored as raw marker data here: https://zenodo.org/records/13030

I don't think I have a copy of the processed data (but maybe I could dig in some old hard drives). We can also process it with GaitAnalysisToolKit. The only issue is that Pandas removed the Panel object in version 0.25 which is a primary data type used in GaitAnalysisToolKit, so this means that the newest Python version GaitAnalysisToolKit works with it Python 3.7. But we can process the old data using Python 3.7 and GTK.

**Comment by tvdbogert** [comment]
Let's consider tracking raw marker data instead of processed data.  

We only care about the model's motion getting as close as possible to the human data. Then the tracking cost can simply omit any missing marker data and it's very clean without tricks and assumptions.

We have markers approximately on the joint centers of the 2D model (which is what we also assumed in the GaitAnalysisToolKit), so the forward kinematics is quite easy to get the model's marker trajectories in the simulation.

For marker tracking to work well, we need to scale the model to have the same dimensions as the human participant.  Should be quite straightforward by calculating mean bone lengths from the marker data.

We don't have to decide yet, there is other work to do first.  As promised, I will write an outline on the wiki.

**Comment by tvdbogert** [comment]
Marker locations in the model is easy to do.

Yes, for the open loop method, we need angles, angular rates, and torques, so it's good you got that working again.

**Comment by moorepants** [comment]
How to generate the processed data from 2015.

Clone: https://github.com/csu-hmc/gait-control-direct-id-paper

Set up a working environment with the old packages that can run the GaitAnalysisToolKit, see: https://github.com/csu-hmc/GaitAnalysisToolKit/issues/150 (also install GTK into that environment).

Download the data to a "raw" data directory somewhere on your computer.

Then run this script: https://github.com/csu-hmc/gait-control-direct-id-paper/blob/master/src/prep_data_for_identification_with_plots.py

Which will need a few fixes to get things to work now:

- change yaml.load() commands to include a loader (SafeLoader)
- comment out the call to hist()

**Comment by moorepants** [comment]
I've created the processed data h5 files and now (with an old Pandas version) you can do:

```
d = pd.read_hdf('020-longitudinal-perturbation.h5', 'gait_cycles')
d[0].to_csv(filename)
```

to write a single gait cycle from a trial to a csv file. To make these easier to use, I could create csv files of this processed data. Sorting all gait cycles in a single csv could be done if there was a new column numbering the gait cycles.

**Comment by moorepants** [comment]
After running [prep_data_for_identification_with_plots.py](https://github.com/csu-hmc/gait-control-direct-id-paper/blob/master/src/prep_data_for_identification_with_plots.py), there is the `processed-data/gait-data` directory that contains the h5 files which have all of the processed data. The following lines generate a csv file from the `gait-cycles` Panel, which we can use as
```
import pandas as pd
d = pd.read_hdf('020-longitudinal-perturbation.h5', 'gait_cycles')
d.transpose(2, 0, 1).to_frame().to_csv('020-longitudinal-perturbation-gait-cycles.csv')
```

[Download the file(https://drive.google.com/file/d/1rsBbDih0fqa8v14fmY7__Ss01eaY7Ol9/view?usp=sharing) [16mb].

Trial 20 has this meta data:

```yaml
study:
        id: 1
        name: Gait Control Identification
        description: Perturb the subject during walking and running.
subject:
        id: 8
        age: 20
        mass: 70
        mass-units: kilograms
        height: 1.572
        height-units: meters
        knee-width-left: 107.43
        knee-width-right: 107.41
        knee-width-units: millimeters
        ankle-width-left: 70.52
        ankle-width-right: 67.66
        ankle-width-units: millimeters
        gender: male
trial:
        id: 20
        subject-id: 8
        datetime: 2014-02-21
        notes: >
                This is the trial run for the 10 minute protocol that perturbs
                the subject longitudinally for 8 minutes. It includes normal
                walking and walking under longitudinal perturbations. The
                treadmill reference markers were not in place due to
                conflicting marker issues with the markers on the human. We
                have the metal feet placed under the four corners of the
                treadmill to prevent pitch and sway movements. We also have
                +/-3g analog accelerometers (ADXL330) affixed to the four
                corners of the main frame of the treadmill and wired into the
                NI box.
        nominal-speed: 1.2
        nominal-speed-units: meters per second
        stationary-platform: True
        pitch: False
        sway: False
        marker-set: full
        hardware-settings:
                high-performance: True
        dflow-version: 3.16.1
        cortex-version: 3.1.1.1290
        analog-channel-map:
                Channel1.Anlg: F1Y1
                Channel2.Anlg: F1Y2
                Channel3.Anlg: F1Y3
                Channel4.Anlg: F1X1
                Channel5.Anlg: F1X2
                Channel6.Anlg: F1Z1
                Channel7.Anlg: F2Y1
                Channel8.Anlg: F2Y2
                Channel9.Anlg: F2Y3
                Channel10.Anlg: F2X1
                Channel11.Anlg: F2X2
                Channel12.Anlg: F2Z1
                Channel61.Anlg: Front_Left_AccX
                Channel62.Anlg: Front_Left_AccY
                Channel63.Anlg: Front_Left_AccZ
                Channel64.Anlg: Back_Left_AccX
                Channel65.Anlg: Back_Left_AccY
                Channel66.Anlg: Back_Left_AccZ
                Channel67.Anlg: Front_Right_AccX
                Channel68.Anlg: Front_Right_AccY
                Channel69.Anlg: Front_Right_AccZ
                Channel70.Anlg: Back_Right_AccX
                Channel71.Anlg: Back_Right_AccY
                Channel72.Anlg: Back_Right_AccZ
        events:
                A: Force Plate Zeroing
                B: Calibration Pose
                C: First Normal Walking
                D: Longitudinal Perturbation
                E: Second Normal Walking
                F: Unloaded End
        files:
                compensation: ../T023/mocap-023.txt
                mocap: mocap-020.txt
                record: record-020.txt
                meta: meta-020.yml
```
